# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatStaGram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatStaGram
  pod 'Alamofire'
  target 'CatStaGramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatStaGramUITests' do
    # Pods for testing
  end

end
